version: '${DOCKER_VERSION}'

networks:
  my_network:
    #external: true
    name: ${NETWORKS}

services:

  frontend:
    env_file:
      - ${ENV_FILE}
    container_name: '${CONTAINER_PREFIX}${FRONTEND_CONTAINER_SUFFIX}'
    build: 
      context: ./docker/frontend
      dockerfile: ./Dockerfile
      args:
        NPM: ${NPM}
        NODEJS: ${NODEJS}
        APP_FRONTEND_PORT: ${APP_FRONTEND_PORT}
    volumes:
      - ./docker/frontend/codebase:/app
      - /app/node_modules
    ports:
      - '${LOCALHOST}:${APP_FRONTEND_PORT}:${APP_FRONTEND_PORT}'
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
    networks:
      my_network: {}

  server:
    env_file:
      - ${ENV_FILE}
    container_name: '${CONTAINER_PREFIX}${BACKEND_CONTAINER_SUFFIX}'
    build:
      context: ./docker/server
      dockerfile: ./Dockerfile
      args:
        PROJECT_NAME_LOWERCASE: ${PROJECT_NAME_LOWERCASE}
        USER_UID: ${USER_UID}
        PHP_VERSION: ${PHP_VERSION}
    ports:
      - '${LOCALHOST}:${APP_BACKEND_PORT}:80'
    working_dir: /var/www/html
    user: user${PROJECT_NAME_LOWERCASE}
    environment:
      - 'DATABASE_URL=mysql://${DB_USER}:${DB_PASSWORD}@db_server:3306/${DB_PROJECT_NAME}?serverVersion=${DB_SERVER_VERSION}'
    volumes:
      - ./docker/server/codebase:/var/www/html
      - ./docker/server/apache/sites-enabled:/etc/apache2/sites-enabled
      - ./docker/server/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
    depends_on:
      db_server:
        condition: service_healthy
    networks:
      my_network: {}

  db_server:
    image: ${DB_IMAGE}:${DB_SERVER_VERSION}
    container_name: '${CONTAINER_PREFIX}${DB_CONTAINER_SUFFIX}'
    restart: always
    ports:
      - '${APP_DB_PORT}:3306'
    environment:
      MARIADB_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MARIADB_USER: '${DB_USER}'
      MARIADB_PASSWORD: '${DB_PASSWORD}'
      MARIADB_DATABASE: '${DB_PROJECT_NAME}'
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: mysqladmin ping -h ${LOCALHOST} -u root --password=${DB_ROOT_PASSWORD}
      interval: ${DB_HEALTHCHECK_INTERVAL}
      retries: ${DB_HEALTHCHECK_RETRIES}
    networks:
      my_network: {}

  db_admin:
    image: phpmyadmin/phpmyadmin:5
    container_name: '${CONTAINER_PREFIX}${DB_ADMIN_CONTAINER_SUFFIX}'
    ports:
      - '${LOCALHOST}:${APP_DB_ADMIN_PORT}:80'
    environment:
      PMA_HOST: db_server
    depends_on:
      db_server:
        condition: service_healthy
    volumes:
      - db_admin_data:/var/www/html
    networks:
      my_network: {}

volumes:
  db_data:
  db_admin_data:

